SIZE_UNIT = 8
GRID_WIDTH = 31
GRID_HEIGHT = 23

WINDOW_WIDTH = GRID_WIDTH * SIZE_UNIT + 1
WINDOW_HEIGHT = GRID_HEIGHT * SIZE_UNIT + 1

STAGE_GOAL = 400
CLEAR_RATE = 0.9
BLOCK_LIFE = 300
WATER_SPEED = 1
MAX_WATER = 400
MAX_STRESS = 250
LATERAL_FLOW_SEARCH_DEPTH = 4
ENABLE_DIAGONAL_FALL = True
UPWARD_SPLASH_CHANCE = 0.08
RESET_COOLDOWN_FRAMES = 10
DEBUG_MODE = False
RANDOM_SEED = 0
DEFAULT_STAGE_NUMBER = 1
STAGE_DIRECTORY = "distillate_stages"
STAGE_FILE_GLOB = "stage_*.dat"

C_BLACK = 0
C_GREEN = 3
C_BROWN = 4
C_BLUE = 6
C_WHITE = 7
C_YELLOW = 10
C_GRAY = 13
C_RED = 14
C_PALE = 15
